<?php
echo '
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PHP with HTML</title>
</head>
<body>
    <h1>Welcome to my page</h1>
    <p><b>This content is generated by <i>PHP</i>.</b></p>
    <p>My name is <b>Nihar Pentapalli</b>.<br>My AMP Stack journey begins here!</p>
</body>
</html>
';
?>

